# Generated by Django 5.1.7 on 2025-03-21 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoolRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stool_type', models.CharField(choices=[('type1', 'Type 1 - Separate hard lumps'), ('type2', 'Type 2 - Sausage-shaped but lumpy'), ('type3', 'Type 3 - Sausage-shaped with cracks'), ('type4', 'Type 4 - Smooth and soft'), ('type5', 'Type 5 - Soft blobs with clear-cut edges'), ('type6', 'Type 6 - Fluffy pieces with ragged edges'), ('type7', 'Type 7 - Entirely liquid')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
