# Generated by Django 5.1.7 on 2025-05-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoolrecord',
            name='pain',
            field=models.BooleanField(default=False, help_text='Check if experiencing pain'),
        ),
    ]
