# Generated by Django 5.1.7 on 2025-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stool', '0004_alter_stoolrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoolrecord',
            name='blood_in_stool',
            field=models.BooleanField(default=False, help_text='Check if blood is visible in the stool'),
        ),
        migrations.AddField(
            model_name='stoolrecord',
            name='blood_on_paper',
            field=models.BooleanField(default=False, help_text='Check if blood is visible on toilet paper'),
        ),
    ]
